**As** a user of this project

**I want** to be implement a feature

**So that** so the project becomes more attractive

## Acceptance Criteria
- required for every feature

**NOTES**
- Possible solution:
- Influencers
- Previous attempts
